### ISSUE TITLE
Enum

### ISSUE THREAD

**Issue by mbiernaczyk** [Drakles/creditAgricole#3]
https://github.com/Drakles/creditAgricole/blob/91d722a1c576b20de5516c860bb74e242fb3c934/src/main/java/com/packt/ticketMachine/tickets/SingleTicket.java#L14

Nie wiadomo, co to jest 1, co 2. Zdefiniować odpowiednie stałe
private final static int JEDEN_TO_COS = 1
private final static int DWA_TO_COS_INNEGO = 2

**Comment by mbiernaczyk** [comment]
W zasadzie to mogłyby być podklasy dla NormalSingleTicket, SpecialSingleTicket

**Comment by Drakles** [comment]
a nie lepiej zostawić tylko komentarz ?
Podklas nie będę robił bo chciałbym być spójny z TimeTicket a tam chyba nie ma sensu robić 4 podklas

**Comment by mbiernaczyk** [comment]
Ja bym robił podklasy dla każdego biletu.

**Comment by SzymonPajzert** [comment]
Podklasy to dobry pomysł, gdzie ten enum jest użyty co jest teraz zdefiniowany?
