### ISSUE TITLE
Stałe

### ISSUE THREAD

**Issue by mbiernaczyk** [Drakles/creditAgricole#6]
https://github.com/Drakles/creditAgricole/blob/91d722a1c576b20de5516c860bb74e242fb3c934/src/main/java/com/packt/ticketMachine/tickets/Prices.java#L6

To jest ok, żeby mieć klasę ze stałym, skoro są final, to zrób je publiczne i usuń gettery.
W zasadzie mógłbyś się pozbyć tej klasy w ogóle, mają klasę dla każdego rodzaju biletu i definując te ceny bezpośredio w nich. To już zależy czy chcesz, aby były w jednym miejscu czy nie koniecznie.

**Comment by Drakles** [comment]
Wole zostawić w jednym miejscu, ale gettery usunę :D
